name: Publish Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions: 
      id-token: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up uv with caching
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "**/uv.lock"

      - name: Install dependencies
        run: uv sync

      - name: Build package
        run: uv build

      - name: Publish package to PyPI
        run: uv publish
